sudo: required
language: java
jdk: openjdk8
dist: xenial

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.npm/

branches:
  only:
    - master
    - "2.0"

before_install:
  - cp settings.xml ~/.m2/
  - nvm install 14

install:
  - npm install
  - node createFrontend.js
  - rm src/main/resources/META-INF/resources/frontend/example-data-bundle.js
  - node_modules/.bin/rollup -c 

script: 
  - mvn package -Pdirectory
