sudo: required
language: java
jdk: openjdk8
dist: xenial

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.npm/

branches:
  only:
    - master
    - "2.0"

before_install:
  - cp settings.xml ~/.m2/
  - nvm install 14

install:
  - npm install
  - node createFrontend.js
  - rm -f src/main/resources/META-INF/frontend/example-data-bundle.*
  - cat src/main/resources/META-INF/resources/frontend/data-generator.ts|sed "s/example-data-bundle/example-data-bundle.esm/" > src/main/resources/META-INF/resources/frontend/data-generator.esm.ts
  - node_modules/.bin/rollup -c rollup.config.cjs.js
  - node_modules/.bin/rollup -c rollup.config.esm.js

script: 
  - mvn package -Pdirectory
